import assureicon from './Livingroom/LRimages/benefit.png'

export const Alldatas=[{
    id:1,
    amount:1,
cat:"liv",
itemsecname:'Decorhand Modern',
    itemimages : 'https://www.ulcdn.net/images/products/808355/product/contour_chair_and_ottoman_replica_indigo_patch_replace_LP.png?1683920953',
    itemname : 'Decorhand Modern Accent Rest Chair for Relax at Home',
    itemcolor:'Finish Color - NavyBlue, Pre-assembled',
    itemassureicon:assureicon,
    itemassurance : 'Assure',
    itemdisrate : 10999,
    itenrate :9999,
    itemdispers: "75% off",
    itemdelivery:'Free delivery',
    itembankdetails:'EMI Available'
    
},
{id:2,
    amount:1,
    cat:"liv",
    itemsecname:'Jarrah Solid Wood',
    itemimages : 'https://www.ulcdn.net/images/products/809981/product/FVTBAV62BR24375_LP.jpg?1684135509',
    itemname : 'Jarrah Solid Wood Free Standing TV Unit In Melamine Finish',
    itemcolor:'Finish Color - NavyBlue, Pre-assembled',
    itemassureicon:assureicon,
    itemassurance : 'Assure',
    itemdisrate : 21000,
    itenrate :25000,
    itemdispers: "55% off",
    itemdelivery:'Free delivery',
    itembankdetails:'EMI Available'
    
},{id:3,
    amount:1,
    cat:"liv",
    itemsecname:'Epsilon Solid Wood',
    itemimages : 'https://www.ulcdn.net/images/products/808496/product/Epsilon_Console_Table_TK_LP.png?1683921375',
    itemname : 'Epsilon Solid Wood Console Table In Teak Finish',
    itemcolor:'Finish Color - woodpaint, Pre-assembled',
    itemassureicon:assureicon,
    itemassurance : 'Assure',
    itemdisrate : 9500,
    itenrate :8999,
    itemdispers: "75% off",
    itemdelivery:'Free delivery',
    itembankdetails:'EMI Available'
    
},{id:4,
    amount:1,
    cat:"liv",
    itemsecname:'Theodore Engineered',
    itemimages : 'https://www.ulcdn.net/images/products/808651/product/FNSGDR33RW15129_LP.png?1683921870',
    itemname : 'Theodore Engineered Wood Bookshelf In Rustic Walnut Finish',
    itemcolor:'Finish Color - NavyBlue, Pre-assembled',
    itemassureicon:assureicon,
    itemassurance : 'Assure',
    itemdisrate : 34000,
    itenrate :29000,
    itemdispers: "75% off",
    itemdelivery:'Free delivery',
    itembankdetails:'EMI Available'
    
},
// export const diningroomcards=[
    {
    id:5,
    amount:1,
    cat:"din",
    itemsecname:'Brighton Capra',
    itemimages : 'https://www.ulcdn.net/images/products/258424/product/Lawson_6_Seater_Dining_Table_Set_LP.jpg?1550722290',
    itemname : 'Brighton Capra Solid Wood 4 Seater Dining Table With Set Of Chairs In Teak Finish',
    itemcolor:'Finish Color - wood, Pre-assembled',
    itemassureicon:assureicon,
    itemassurance : 'Assure',
    itemdisrate : 36000,
    itenrate :32000,
    itemdispers: "80% off",
    itemdelivery:'Free delivery',
    itembankdetails:'EMI Available'
},{
    id:6,
    amount:1,
    cat:"din",
    itemsecname:'Martha Solid Wood',
    itemimages : 'https://www.ulcdn.net/images/products/809292/product/Martha_Dining_Chairs_Mahogany_Burnt_Orange_newLP.png?1683923600',
    itemname : 'Martha Solid Wood Dining Chair Set Of 2 In Mahogany Finish',
    itemcolor:'Finish Color - wood, Pre-assembled',
    itemassureicon:assureicon,
    itemassurance : 'Assure',
    itemdisrate : 4000,
    itenrate :3750,
    itemdispers: "65% off",
    itemdelivery:'Free delivery',
    itembankdetails:'EMI Available'
},{
    id:7,
    amount:1,
    cat:"din",
    itemsecname:'Levi Cotton Grey',
    itemimages : 'https://www.ulcdn.net/images/products/485010/product/VDSTCP88GE25799_Grey_LP.jpg?1648219264',
    itemname : 'Levi Cotton Grey Solid 16x16 Inches Polyfill Filled Chair Pad',
    itemcolor:'Finish Color - NavyBlue, Pre-assembled',
    itemassureicon:assureicon,
    itemassurance : 'Assure',
    itemdisrate : 1250,
    itenrate :950,
    itemdispers: "35% off",
    itemdelivery:'Free delivery',
    itembankdetails:'EMI Available'
},{
    id:8,
    amount:1,
    cat:"din",
    itemsecname:'Riveria Solid Wood',
    itemimages : 'https://www.ulcdn.net/images/products/809467/product/Riveria_Solid_Wood_Bar_Cabinet_Mahogany_LP.png?1683924053',
    itemname : 'Riveria Solid Wood Free Standing Bar Cabinet In Mahogany Finish',
    itemcolor:'Finish Color - NavyBlue, Pre-assembled',
    itemassureicon:assureicon,
    itemassurance : 'Assure',
    itemdisrate : 55000,
    itenrate :45000,
    itemdispers: "65% off",
    itemdelivery:'Free delivery',
    itembankdetails:'EMI Available'
},


// export const bedroomdatas=[
    {
    id:9,
    amount:1,
    cat:"bed",
    itemsecname:'Boston Solid Wood',
    itemimages : 'https://www.ulcdn.net/images/products/835312/product/FNCOMB11MH31926_LP_copy.png?1689767302',
    itemname : 'Boston Solid Wood King Size Box Storage Bed In Teak Finish',
    itemcolor:'Finish Color - teak, Pre-assembled',
    itemassureicon:assureicon,
    itemassurance : 'Assure',
    itemdisrate : 83000,
    itenrate :53000,
    itemdispers: "38% off",
    itemdelivery:'Free delivery',
    itembankdetails:'EMI Available'
},{
    id:10,
    amount:1,
    cat:"bed",
    itemsecname:'Amber Engineered',
    itemimages : 'https://www.ulcdn.net/images/products/808150/product/Amber_Dresser_LP_copy.png?1683919687',
    itemname : 'Amber Engineered Wood Dressing Table In Brown Finish',
    itemcolor:'Finish Color - wood, Pre-assembled',
    itemassureicon:assureicon,
    itemassurance : 'Assure',
    itemdisrate : 21000,
    itenrate :25000,
    itemdispers: "55% off",
    itemdelivery:'Free delivery',
    itembankdetails:'EMI Available'
},{
    id:11,
    amount:1,
    cat:"bed",
    itemsecname:'Hilton Engineered',
    itemimages : 'https://www.ulcdn.net/images/products/809190/product/Hilton_4_Door_2_Drawer_Wardrobe_finish_Spiced_acacia_merc_lp.png?1683923328',
    itemname : 'Hilton Engineered Wood 4 Door Wardrobe With Mirror In Spiced Acacia Finish',
    itemcolor:'Finish Color - wood, Pre-assembled',
    itemassureicon:assureicon,
    itemassurance : 'Assure',
    itemdisrate : 40000,
    itenrate :35000,
    itemdispers: "55% off",
    itemdelivery:'Free delivery',
    itembankdetails:'EMI Available'
},{
    id:12,
    amount:1,
    cat:"bed",
    itemsecname:'Engineered Wood',
    itemimages : 'https://www.ulcdn.net/images/products/808243/product/Brent__Crib_Finish_mint_Green_LP.png?1683920660',
    itemname : 'Engineered Wood Crib In White Colour',
    itemcolor:'Finish Color - wood, Pre-assembled',
    itemassureicon:assureicon,
    itemassurance : 'Assure',
    itemdisrate : 27000,
    itenrate :25999,
    itemdispers: "55% off",
    itemdelivery:'Free delivery',
    itembankdetails:'EMI Available'
},
// export const kitchencards=[
    {
    id:13,
    amount:1,
    cat:"kit",
    itemsecname:'Hubert 6 Door',
    itemimages : 'https://www.ulcdn.net/images/products/829377/product/FNSGBR33BR35937_LP.png?1687948941',
    itemname : 'Hubert 6 Door Kitchen Display Cabinet',
    itemcolor:'Finish Color - woodpaint, Pre-assembled',
    itemassureicon:assureicon,
    itemassurance : 'Assure',
    itemdisrate : 46999,
    itenrate :44999,
    itemdispers: "75% off",
    itemdelivery:'Free delivery',
    itembankdetails:'EMI Available'
},{
    id:14,
    amount:1,
    cat:"kit",
    itemsecname:'jeevis black hell',
    itemimages : 'https://www.ulcdn.net/images/products/816372/product/Jeeves_Kitchen_Rack_Walnut_Finish_img_5319_copy_LP.png?1684836303',
    itemname : 'jeevis black hell rack wood',
    itemcolor:'Finish Color - woodpaint, Pre-assembled',
    itemassureicon:assureicon,
    itemassurance : 'Assure',
    itemdisrate : 9500,
    itenrate :8999,
    itemdispers: "75% off",
    itemdelivery:'Free delivery',
    itembankdetails:'EMI Available'
},{
    id:15,
    amount:1,
    cat:"kit",
    itemsecname:'Epsilon Solid',
    itemimages : 'https://www.ulcdn.net/images/products/808890/product/FVBRBU62WA20144_LP.png?1683922582',
    itemname : 'Epsilon Solid Wood Console Table In Teak Finish',
    itemcolor:'Finish Color - woodpaint, Pre-assembled',
    itemassureicon:assureicon,
    itemassurance : 'Assure',
    itemdisrate : 9500,
    itenrate :8999,
    itemdispers: "75% off",
    itemdelivery:'Free delivery',
    itembankdetails:'EMI Available'
},{
    id:16,
    amount:1,
    cat:"kit",
    itemsecname:'Dante Solid Wood',
    itemimages : 'https://www.ulcdn.net/images/products/808341/product/Dante_Bar_Cabinet_LP.png?1683920937',
    itemname : 'Dante Solid Wood Bar Cabinet In Finish',
    itemcolor:'Finish Color - woodpaint, Pre-assembled',
    itemassureicon:assureicon,
    itemassurance : 'Assure',
    itemdisrate : 12000,
    itenrate :10000,
    itemdispers: "75% off",
    itemdelivery:'Free delivery',
    itembankdetails:'EMI Available'
},
// export const storeroomdatas=[
    {
    id:17,
    amount:1,
    cat:"sto",
    itemsecname:'Rhodes Solid Wood',
    itemimages : 'https://www.ulcdn.net/images/products/809474/product/Rhodes_Storage_Chest_AW_00_LP.png?1683924063',
    itemname : 'Rhodes Solid Wood Bench In Amber Walnut Finish',
    itemcolor:'Finish Color - woodpaint, Pre-assembled',
    itemassureicon:assureicon,
    itemassurance : 'Assure',
    itemdisrate : 9500,
    itenrate :8999,
    itemdispers: "75% off",
    itemdelivery:'Free delivery',
    itembankdetails:'EMI Available'
},{
    id:18,
    amount:1,
    cat:"sto",
    itemsecname:'Nitara Solid Wood',
    itemimages : 'https://www.ulcdn.net/images/products/809376/product/Nitara_Blanket_box_Finish-Mahogany_LP.png?1683923839',
    itemname : 'Nitara Solid Wood Blanket Box',
    itemcolor:'Finish Color - woodpaint, Pre-assembled',
    itemassureicon:assureicon,
    itemassurance : 'Assure',
    itemdisrate : 11500,
    itenrate :10999,
    itemdispers: "75% off",
    itemdelivery:'Free delivery',
    itembankdetails:'EMI Available'
},{
    id:19,
    amount:1,
    cat:"sto",
    itemsecname:'Epsilon Solid Wood',
    itemimages : 'https://www.ulcdn.net/images/products/816373/product/FNSGSB41WL30062_LP.png?1684836304',
    itemname : 'Epsilon Solid Wood Console Table In Teak Finish',
    itemcolor:'Finish Color - woodpaint, Pre-assembled',
    itemassureicon:assureicon,
    itemassurance : 'Assure',
    itemdisrate : 9500,
    itenrate :8999,
    get : "5641654",
    itemdispers: "75% off",
    itemdelivery:'Free delivery',
    itembankdetails:'EMI Available'
},{
    id:20,
    amount:1,
    cat:"sto",
    itemsecname:'Azul Solid Wood',
    itemimages : 'https://www.ulcdn.net/images/products/808659/product/FNSGSB62BO15809_LP.png?1683921875',
    itemname : 'Azul Solid Wood Sideboard In Brushed Bali Oak Finish',
    itemcolor:'Finish Color - woodpaint, Pre-assembled',
    itemassureicon:assureicon,
    itemassurance : 'Assure',
    itemdisrate : 39500,
    itenrate :38999,
    itemdispers: "75% off",
    itemdelivery:'Free delivery',
    itembankdetails:'EMI Available'
    },

]